### ISSUE TITLE
Badge position is not done yet.

### ISSUE THREAD

**Issue by westdabestdb** [westdabestdb/bottom_navigation_badge#1]
Badge position variable is available but it's not functional yet. Only position is working right now is top right.

**Comment by mrleesin** [comment]
Is it possible to make right more right? ) Now its slightly right from center

**Comment by westdabestdb** [comment]
Sure, everything can be righter haha 😁 Will do better position alignments!

**Comment by mrleesin** [comment]
waiting for that!!

**Comment by westdabestdb** [comment]
Solved with [commit](https://github.com/westdabestdb/bottom_navigation_badge/commit/297ef339967d08433a7f6345c013c499effe6fd2#diff-325f45e453bcbfa9f151a6b6e37af887).

**Comment by dukaric1991** [comment]
Can i slightly move red dot more right than current top-right position?

**Comment by westdabestdb** [comment]
Hello @mrleesin @dukaric1991, thank you for using the package.I just published a minor release that covers "make the right more right" hehe 😁. [Check for the reference](https://imgur.com/hYpyrDo) and compare with the GIF in the README.
