### ISSUE TITLE
bottom_navigation_badge activeIcon color

### ISSUE THREAD

**Issue by k3sc** [westdabestdb/bottom_navigation_badge#2]
The color of activeIcon will not be displayed after use

**Comment by k3sc** [comment]
![image](https://user-images.githubusercontent.com/28189393/60488143-c645b380-9cd3-11e9-8e01-ec5c73d813d1.png)

**Comment by westdabestdb** [comment]
Why this is closed without proper communication or explanation?

**Comment by k3sc** [comment]
Sorry, my English is very poor,Why is this problem closed?Because I solved this problem by adding this sentence to the source code. @westdabestdb
